# Generated by Django 2.1.7 on 2019-07-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190731_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
